drop table if exists eatery;
create table eatery (
    name text,
    location text,
    park_id text,
    start_date date,
    end_date date,
    description text,
    permit_number text,
    phone text,
    website text,
    type_name text);
ALTER TABLE eatery
ADD eatery_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;